# This file is auto-generated by scripts/gen_namespaces.py from scavio/_spec.py.
# Do NOT edit by hand: edit the spec and re-run `python scripts/gen_namespaces.py`.
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Optional

if TYPE_CHECKING:
    from ._client import ScavioClient

__all__ = [
    "_GoogleNamespace",
    "_AmazonNamespace",
    "_WalmartNamespace",
    "_YouTubeNamespace",
    "_RedditNamespace",
    "_TikTokNamespace",
    "_InstagramNamespace",
]

class _GoogleNamespace:
    """Google endpoints (SERP, Maps, Shopping, Flights, Hotels, News, Trends)."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def search(
        self,
        query: str,
        *,
        device: Optional[Literal["desktop", "mobile"]] = None,
        start: Optional[int] = None,
        include_html: Optional[bool] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        google_domain: Optional[str] = None,
        location: Optional[str] = None,
        uule: Optional[str] = None,
        lr: Optional[str] = None,
        cr: Optional[str] = None,
        safe: Optional[Literal["active"]] = None,
        nfpr: Optional[bool] = None,
        filter: Optional[Literal["0", "1"]] = None,
        time_period: Optional[Literal["last_hour", "last_day", "last_week", "last_month", "last_year"]] = None,
        resolve_ai_overview: Optional[bool] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google SERP search (organic results, ads, and the AI Overview when present).

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Search query (1-500 characters).
            device: Device to emulate.
            start: Result offset: 0 = page 1, 10 = page 2, ... up to 990.
            include_html: Include the raw Google HTML in the response.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            location: Canonical location name; auto-encoded to a UULE string.
            uule: Pre-encoded UULE location string (takes priority over location).
            lr: Language restrict (e.g. 'lang_en').
            cr: Country restrict (e.g. 'countryUS').
            safe: SafeSearch filter.
            nfpr: Disable spelling correction / auto-fixes when True.
            filter: '0' disables the omitted/similar-results filter.
            time_period: Restrict results to a recent time window.
            resolve_ai_overview: Resolve a deferred AI Overview (server default True).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_search", {"query": query, "device": device, "start": start, "include_html": include_html, "hl": hl, "gl": gl, "google_domain": google_domain, "location": location, "uule": uule, "lr": lr, "cr": cr, "safe": safe, "nfpr": nfpr, "filter": filter, "time_period": time_period, "resolve_ai_overview": resolve_ai_overview}, extra)

    def ai_mode(
        self,
        query: str,
        *,
        device: Optional[Literal["desktop", "mobile"]] = None,
        include_html: Optional[bool] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        google_domain: Optional[str] = None,
        location: Optional[str] = None,
        uule: Optional[str] = None,
        safe: Optional[Literal["active"]] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google AI Mode conversational answer with references.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Question or prompt (1-500 characters).
            device: Device to emulate.
            include_html: Include the raw Google HTML in the response.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            location: Canonical location name; auto-encoded to a UULE string.
            uule: Pre-encoded UULE location string (takes priority over location).
            safe: SafeSearch filter.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_ai_mode", {"query": query, "device": device, "include_html": include_html, "hl": hl, "gl": gl, "google_domain": google_domain, "location": location, "uule": uule, "safe": safe}, extra)

    def maps_search(
        self,
        query: str,
        *,
        start: Optional[int] = None,
        ll: Optional[str] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        google_domain: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Maps local business results.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Search query (1-500 characters).
            start: Result offset; must be a multiple of 20 (0, 20, 40, ...).
            ll: Map center as '@lat,lng,zoomz'; controls where results come from.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_maps_search", {"query": query, "start": start, "ll": ll, "hl": hl, "gl": gl, "google_domain": google_domain}, extra)

    def maps_place(
        self,
        *,
        place_id: Optional[str] = None,
        data_cid: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Maps place details. Provide place_id or data_cid.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            place_id: Place ID (ChIJ...).
            data_cid: Numeric CID.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_maps_place", {"place_id": place_id, "data_cid": data_cid}, extra)

    def maps_reviews(
        self,
        *,
        data_id: Optional[str] = None,
        place_id: Optional[str] = None,
        num: Optional[int] = None,
        next_page_token: Optional[str] = None,
        sort_by: Optional[Literal["relevance", "newest", "highest_rating", "lowest_rating"]] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        google_domain: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Maps reviews for a place. Provide data_id or place_id.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            data_id: Data ID (0xHEX:0xHEX).
            place_id: Place ID (ChIJ...).
            num: Reviews per page (1-20).
            next_page_token: Pagination cursor from a prior response.
            sort_by: Sort order.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_maps_reviews", {"data_id": data_id, "place_id": place_id, "num": num, "next_page_token": next_page_token, "sort_by": sort_by, "hl": hl, "gl": gl, "google_domain": google_domain}, extra)

    def shopping(
        self,
        query: str,
        *,
        device: Optional[Literal["desktop", "mobile"]] = None,
        start: Optional[int] = None,
        min_price: Optional[int] = None,
        max_price: Optional[int] = None,
        sort_by: Optional[int] = None,
        free_shipping: Optional[bool] = None,
        on_sale: Optional[bool] = None,
        shoprs: Optional[str] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        google_domain: Optional[str] = None,
        location: Optional[str] = None,
        uule: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Shopping product listings.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Product search query (1-500 characters).
            device: Device to emulate.
            start: Result offset.
            min_price: Minimum price filter.
            max_price: Maximum price filter.
            sort_by: 0 = relevance, 1 = price ascending, 2 = price descending.
            free_shipping: Only items with free shipping.
            on_sale: Only items on sale.
            shoprs: Opaque Google Shopping filter token.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            location: Canonical location name; auto-encoded to a UULE string.
            uule: Pre-encoded UULE location string (takes priority over location).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_shopping", {"query": query, "device": device, "start": start, "min_price": min_price, "max_price": max_price, "sort_by": sort_by, "free_shipping": free_shipping, "on_sale": on_sale, "shoprs": shoprs, "hl": hl, "gl": gl, "google_domain": google_domain, "location": location, "uule": uule}, extra)

    def shopping_product(
        self,
        *,
        catalog_id: Optional[str] = None,
        query: Optional[str] = None,
        immersive_product_page_token: Optional[str] = None,
        page_token: Optional[str] = None,
        product_id: Optional[str] = None,
        device: Optional[Literal["desktop", "mobile", "tablet"]] = None,
        google_domain: Optional[str] = None,
        sort_by: Optional[Literal["base_price", "total_price", "promotion", "seller_rating"]] = None,
        load_all_stores: Optional[bool] = None,
        more_stores: Optional[bool] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        location: Optional[str] = None,
        uule: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Shopping product detail and sellers. Pass catalog_id + query for full data.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            catalog_id: Durable product catalog id.
            query: Product query; required when catalog_id is set.
            immersive_product_page_token: Immersive product page token.
            page_token: Alias for immersive_product_page_token.
            product_id: Product id.
            device: Device to emulate.
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            sort_by: Seller sort order.
            load_all_stores: Load all available stores.
            more_stores: Fetch additional stores.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            location: Canonical location name; auto-encoded to a UULE string.
            uule: Pre-encoded UULE location string (takes priority over location).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_shopping_product", {"catalog_id": catalog_id, "query": query, "immersive_product_page_token": immersive_product_page_token, "page_token": page_token, "product_id": product_id, "device": device, "google_domain": google_domain, "sort_by": sort_by, "load_all_stores": load_all_stores, "more_stores": more_stores, "hl": hl, "gl": gl, "location": location, "uule": uule}, extra)

    def shopping_stores(
        self,
        catalog_id: str,
        next_page_token: str,
        **extra: Any,
    ) -> dict[str, Any]:
        """More sellers for a shopping product (pagination of shopping_product).

        Costs 1 credit. Returns the API response as a dict.

        Args:
            catalog_id: Durable product catalog id.
            next_page_token: Pagination cursor from shopping_product.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_shopping_stores", {"catalog_id": catalog_id, "next_page_token": next_page_token}, extra)

    def flights(
        self,
        departure_id: str,
        arrival_id: str,
        outbound_date: str,
        *,
        type: Optional[int] = None,
        return_date: Optional[str] = None,
        adults: Optional[int] = None,
        children: Optional[int] = None,
        infants_in_seat: Optional[int] = None,
        infants_on_lap: Optional[int] = None,
        travel_class: Optional[int] = None,
        stops: Optional[int] = None,
        sort_by: Optional[int] = None,
        include_airlines: Optional[str] = None,
        exclude_airlines: Optional[str] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        currency: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Flights search.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            departure_id: Departure IATA code(s); comma-separated allowed.
            arrival_id: Arrival IATA code(s); comma-separated allowed.
            outbound_date: Outbound date (YYYY-MM-DD).
            type: 1 = round trip, 2 = one way, 3 = multi-city.
            return_date: Return date (YYYY-MM-DD); required when type=1.
            adults: Number of adults (1-9).
            children: Number of children (0-9).
            infants_in_seat: Infants in seat (0-4).
            infants_on_lap: Infants on lap (0-4).
            travel_class: 1 = economy, 2 = premium, 3 = business, 4 = first.
            stops: 0 = any, 1 = nonstop, 2 = <=1 stop, 3 = <=2 stops.
            sort_by: 1 = top, 2 = price, 3 = departure, 4 = arrival, 5 = duration, 6 = emissions.
            include_airlines: Comma-separated airline codes/alliances to include.
            exclude_airlines: Comma-separated airline codes/alliances to exclude.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            currency: Currency code (ISO 4217, e.g. 'USD').
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_flights", {"departure_id": departure_id, "arrival_id": arrival_id, "outbound_date": outbound_date, "type": type, "return_date": return_date, "adults": adults, "children": children, "infants_in_seat": infants_in_seat, "infants_on_lap": infants_on_lap, "travel_class": travel_class, "stops": stops, "sort_by": sort_by, "include_airlines": include_airlines, "exclude_airlines": exclude_airlines, "hl": hl, "gl": gl, "currency": currency}, extra)

    def hotels(
        self,
        query: str,
        check_in_date: str,
        check_out_date: str,
        *,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        currency: Optional[str] = None,
        sort_by: Optional[int] = None,
        min_price: Optional[int] = None,
        max_price: Optional[int] = None,
        rating: Optional[int] = None,
        hotel_class: Optional[str] = None,
        amenities: Optional[str] = None,
        property_types: Optional[str] = None,
        free_cancellation: Optional[bool] = None,
        eco_certified: Optional[bool] = None,
        special_offers: Optional[bool] = None,
        next_page_token: Optional[str] = None,
        limit: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Hotels search.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Search query; use a '<City> hotels' form.
            check_in_date: Check-in date (YYYY-MM-DD).
            check_out_date: Check-out date (YYYY-MM-DD).
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            currency: Currency code (ISO 4217, e.g. 'USD').
            sort_by: 3 = lowest price, 8 = highest rating, 13 = most reviewed.
            min_price: Minimum nightly price.
            max_price: Maximum nightly price.
            rating: 7 = 3.5+, 8 = 4.0+, 9 = 4.5+.
            hotel_class: Comma-separated star ratings (2-5).
            amenities: Comma-separated amenity ids.
            property_types: Comma-separated property-type ids (e.g. '12' for vacation rentals).
            free_cancellation: Only properties with free cancellation.
            eco_certified: Only eco-certified properties.
            special_offers: Only properties with special offers.
            next_page_token: Pagination cursor from a prior response.
            limit: Number of properties to return (1-20).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_hotels", {"query": query, "check_in_date": check_in_date, "check_out_date": check_out_date, "hl": hl, "gl": gl, "currency": currency, "sort_by": sort_by, "min_price": min_price, "max_price": max_price, "rating": rating, "hotel_class": hotel_class, "amenities": amenities, "property_types": property_types, "free_cancellation": free_cancellation, "eco_certified": eco_certified, "special_offers": special_offers, "next_page_token": next_page_token, "limit": limit}, extra)

    def hotels_detail(
        self,
        detail_token: str,
        check_in_date: str,
        check_out_date: str,
        *,
        currency: Optional[str] = None,
        gl: Optional[str] = None,
        hl: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Hotels property details, from a hotels listing detail_token.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            detail_token: Property detail token from a hotels listing.
            check_in_date: Check-in date (YYYY-MM-DD).
            check_out_date: Check-out date (YYYY-MM-DD).
            currency: Currency code (ISO 4217, e.g. 'USD').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            hl: UI language (ISO 639-1, e.g. 'en').
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_hotels_detail", {"detail_token": detail_token, "check_in_date": check_in_date, "check_out_date": check_out_date, "currency": currency, "gl": gl, "hl": hl}, extra)

    def news(
        self,
        *,
        query: Optional[str] = None,
        topic_token: Optional[str] = None,
        section_token: Optional[str] = None,
        story_token: Optional[str] = None,
        publication_token: Optional[str] = None,
        kgmid: Optional[str] = None,
        hl: Optional[str] = None,
        gl: Optional[str] = None,
        google_domain: Optional[str] = None,
        so: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google News results. Provide a query or a topic/story/publication token.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Keyword search.
            topic_token: Browse a news topic.
            section_token: Browse a topic section.
            story_token: Fetch full coverage of a story.
            publication_token: Browse a publication.
            kgmid: Knowledge Graph entity id.
            hl: UI language (ISO 639-1, e.g. 'en').
            gl: Country of the search (ISO 3166-1 alpha-2, e.g. 'us').
            google_domain: Regional Google domain (e.g. 'google.co.uk').
            so: Sort order: 0 = relevance, 1 = date (only with query or kgmid).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_news", {"query": query, "topic_token": topic_token, "section_token": section_token, "story_token": story_token, "publication_token": publication_token, "kgmid": kgmid, "hl": hl, "gl": gl, "google_domain": google_domain, "so": so}, extra)

    def trends(
        self,
        query: str,
        *,
        geo: Optional[str] = None,
        hl: Optional[str] = None,
        date: Optional[str] = None,
        tz: Optional[str] = None,
        data_type: Optional[Literal["TIMESERIES", "GEO_MAP", "GEO_MAP_0", "RELATED_QUERIES", "RELATED_TOPICS"]] = None,
        cat: Optional[str] = None,
        gprop: Optional[Literal["images", "news", "youtube", "froogle"]] = None,
        region: Optional[Literal["COUNTRY", "REGION", "DMA", "CITY"]] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Trends interest data.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Search term(s); comma-separated for comparisons.
            geo: Location code (e.g. 'US', 'GB', 'US-CA').
            hl: UI language (ISO 639-1, e.g. 'en').
            date: Time range (e.g. 'today 12-m', 'now 7-d').
            tz: Timezone offset in minutes.
            data_type: Which trends dataset to return.
            cat: Category id.
            gprop: Google property filter.
            region: Resolution for GEO_MAP data.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_trends", {"query": query, "geo": geo, "hl": hl, "date": date, "tz": tz, "data_type": data_type, "cat": cat, "gprop": gprop, "region": region}, extra)

    def trending(
        self,
        geo: str,
        *,
        hl: Optional[str] = None,
        hours: Optional[int] = None,
        cat: Optional[int] = None,
        sort: Optional[Literal["relevance", "search_volume", "recency", "title"]] = None,
        status: Optional[Literal["all", "active"]] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Google Trending Now for a country.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            geo: Country code (e.g. 'US').
            hl: UI language (ISO 639-1, e.g. 'en').
            hours: Trending window: 4, 24, 48, or 168.
            cat: Category id (0-20).
            sort: Sort order.
            status: Filter by trend status.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("google_trending", {"geo": geo, "hl": hl, "hours": hours, "cat": cat, "sort": sort, "status": status}, extra)

class _AmazonNamespace:
    """Amazon product search and lookup endpoints."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def search(
        self,
        query: str,
        *,
        domain: Optional[str] = None,
        country: Optional[str] = None,
        language: Optional[str] = None,
        currency: Optional[str] = None,
        device: Optional[Literal["desktop", "mobile", "tablet"]] = None,
        sort_by: Optional[Literal["most_recent", "price_low_to_high", "price_high_to_low", "featured", "average_review", "bestsellers"]] = None,
        start_page: Optional[int] = None,
        pages: Optional[int] = None,
        category_id: Optional[str] = None,
        merchant_id: Optional[str] = None,
        zip_code: Optional[str] = None,
        autoselect_variant: Optional[bool] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search Amazon product listings.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Product search query (1-500 characters).
            domain: Amazon domain suffix (default 'com', e.g. 'co.uk').
            country: Country code for localization.
            language: Language code.
            currency: Currency code (ISO 4217, e.g. 'USD').
            device: Device to emulate.
            sort_by: Result sort order.
            start_page: Starting page (1-indexed).
            pages: Number of pages to fetch.
            category_id: Amazon category id.
            merchant_id: Filter to a specific merchant.
            zip_code: ZIP/postal code for localized pricing.
            autoselect_variant: Auto-select the default variant.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("amazon_search", {"query": query, "domain": domain, "country": country, "language": language, "currency": currency, "device": device, "sort_by": sort_by, "start_page": start_page, "pages": pages, "category_id": category_id, "merchant_id": merchant_id, "zip_code": zip_code, "autoselect_variant": autoselect_variant}, extra)

    def product(
        self,
        asin: str,
        *,
        domain: Optional[str] = None,
        country: Optional[str] = None,
        language: Optional[str] = None,
        currency: Optional[str] = None,
        device: Optional[Literal["desktop", "mobile", "tablet"]] = None,
        zip_code: Optional[str] = None,
        autoselect_variant: Optional[bool] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Full details for a single Amazon product by ASIN.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            asin: Amazon ASIN (e.g. 'B09XS7JWHH').
            domain: Amazon domain suffix (default 'com').
            country: Country code for localization.
            language: Language code.
            currency: Currency code (ISO 4217, e.g. 'USD').
            device: Device to emulate.
            zip_code: ZIP/postal code for localized pricing.
            autoselect_variant: Auto-select the default variant.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("amazon_product", {"asin": asin, "domain": domain, "country": country, "language": language, "currency": currency, "device": device, "zip_code": zip_code, "autoselect_variant": autoselect_variant}, extra)

    def options(
        self,
    ) -> dict[str, Any]:
        """Supported Amazon domains, languages, currencies, and countries. No API key required.

        No API key required. Returns the API response as a dict.
        """
        return self._client._call("amazon_options", {}, {})

class _WalmartNamespace:
    """Walmart product search and lookup endpoints."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def search(
        self,
        query: str,
        *,
        domain: Optional[str] = None,
        device: Optional[Literal["desktop", "mobile", "tablet"]] = None,
        sort_by: Optional[Literal["best_match", "price_low", "price_high", "best_seller"]] = None,
        start_page: Optional[int] = None,
        min_price: Optional[int] = None,
        max_price: Optional[int] = None,
        fulfillment_speed: Optional[Literal["today", "tomorrow", "2_days", "anytime"]] = None,
        fulfillment_type: Optional[Literal["in_store"]] = None,
        delivery_zip: Optional[str] = None,
        store_id: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search Walmart product listings.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Product search query (1-500 characters).
            domain: Walmart domain.
            device: Device to emulate.
            sort_by: Result sort order.
            start_page: Starting page (1-indexed).
            min_price: Minimum price filter (USD).
            max_price: Maximum price filter (USD).
            fulfillment_speed: Delivery speed filter.
            fulfillment_type: Fulfillment type filter.
            delivery_zip: ZIP code for localized results.
            store_id: Store id for in-store availability.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("walmart_search", {"query": query, "domain": domain, "device": device, "sort_by": sort_by, "start_page": start_page, "min_price": min_price, "max_price": max_price, "fulfillment_speed": fulfillment_speed, "fulfillment_type": fulfillment_type, "delivery_zip": delivery_zip, "store_id": store_id}, extra)

    def product(
        self,
        product_id: str,
        *,
        domain: Optional[str] = None,
        device: Optional[Literal["desktop", "mobile", "tablet"]] = None,
        delivery_zip: Optional[str] = None,
        store_id: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Full details for a single Walmart product.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            product_id: Walmart product id.
            domain: Walmart domain.
            device: Device to emulate.
            delivery_zip: ZIP code for localized pricing.
            store_id: Store id for in-store availability.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("walmart_product", {"product_id": product_id, "domain": domain, "device": device, "delivery_zip": delivery_zip, "store_id": store_id}, extra)

class _YouTubeNamespace:
    """YouTube search and video metadata endpoints."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def search(
        self,
        query: str,
        *,
        upload_date: Optional[Literal["last_hour", "today", "this_week", "this_month", "this_year"]] = None,
        type: Optional[Literal["video", "channel", "playlist"]] = None,
        duration: Optional[Literal["short", "medium", "long"]] = None,
        sort_by: Optional[Literal["relevance", "date", "view_count", "rating"]] = None,
        hd: Optional[bool] = None,
        subtitles: Optional[bool] = None,
        creative_commons: Optional[bool] = None,
        live: Optional[bool] = None,
        hdr: Optional[bool] = None,
        location: Optional[bool] = None,
        vr180: Optional[bool] = None,
        four_k: Optional[bool] = None,
        video_360: Optional[bool] = None,
        video_3d: Optional[bool] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search YouTube videos, channels, and playlists.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            query: Search query (1-500 characters).
            upload_date: Filter by upload date.
            type: Filter by result type.
            duration: short (<4 min), medium (4-20 min), long (>20 min).
            sort_by: Sort order.
            hd: HD videos only.
            subtitles: Videos with subtitles/CC only.
            creative_commons: Creative Commons licensed only.
            live: Live videos only.
            hdr: HDR videos only.
            location: Videos with location metadata only.
            vr180: VR180 videos only.
            four_k: 4K videos only.
            video_360: 360-degree videos only.
            video_3d: 3D videos only.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("youtube_search", {"query": query, "upload_date": upload_date, "type": type, "duration": duration, "sort_by": sort_by, "hd": hd, "subtitles": subtitles, "creative_commons": creative_commons, "live": live, "hdr": hdr, "location": location, "vr180": vr180, "four_k": four_k, "video_360": video_360, "video_3d": video_3d}, extra)

    def metadata(
        self,
        video_id: str,
        **extra: Any,
    ) -> dict[str, Any]:
        """Full metadata for a single YouTube video.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            video_id: YouTube video id (e.g. 'dQw4w9WgXcQ').
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("youtube_metadata", {"video_id": video_id}, extra)

class _RedditNamespace:
    """Reddit search and post endpoints."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def search(
        self,
        query: str,
        *,
        type: Optional[Literal["posts", "comments"]] = None,
        sort: Optional[Literal["new", "relevance", "hot", "top", "comments"]] = None,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search Reddit posts or comments. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            query: Search query (1-500 characters).
            type: Result type (server default 'posts').
            sort: Sort order (server default 'new').
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("reddit_search", {"query": query, "type": type, "sort": sort, "cursor": cursor}, extra)

    def post(
        self,
        url: str,
        **extra: Any,
    ) -> dict[str, Any]:
        """Fetch a Reddit post with its threaded comments. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            url: Full Reddit post URL.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("reddit_post", {"url": url}, extra)

class _TikTokNamespace:
    """TikTok profile, video, hashtag, and search endpoints."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def profile(
        self,
        *,
        username: Optional[str] = None,
        sec_user_id: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """TikTok user profile. Provide username or sec_user_id.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            username: TikTok @username (without the @).
            sec_user_id: TikTok sec_user_id.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_profile", {"username": username, "sec_user_id": sec_user_id}, extra)

    def user_posts(
        self,
        sec_user_id: str,
        *,
        cursor: Optional[str] = None,
        count: Optional[int] = None,
        sort_type: Optional[Literal["0", "1"]] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Videos posted by a TikTok user.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            sec_user_id: TikTok sec_user_id.
            cursor: Pagination cursor (default '0').
            count: Results per page (1-30).
            sort_type: '0' = latest, '1' = popular.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_user_posts", {"sec_user_id": sec_user_id, "cursor": cursor, "count": count, "sort_type": sort_type}, extra)

    def video(
        self,
        video_id: str,
        **extra: Any,
    ) -> dict[str, Any]:
        """Details for a single TikTok video.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            video_id: TikTok video id.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_video", {"video_id": video_id}, extra)

    def video_comments(
        self,
        video_id: str,
        *,
        cursor: Optional[str] = None,
        count: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Comments on a TikTok video.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            video_id: TikTok video id.
            cursor: Pagination cursor (default '0').
            count: Results per page (1-50).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_video_comments", {"video_id": video_id, "cursor": cursor, "count": count}, extra)

    def comment_replies(
        self,
        video_id: str,
        comment_id: str,
        *,
        cursor: Optional[str] = None,
        count: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Replies to a TikTok comment.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            video_id: TikTok video id.
            comment_id: Parent comment id.
            cursor: Pagination cursor (default '0').
            count: Results per page (1-50).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_comment_replies", {"video_id": video_id, "comment_id": comment_id, "cursor": cursor, "count": count}, extra)

    def search_videos(
        self,
        keyword: str,
        *,
        cursor: Optional[str] = None,
        count: Optional[int] = None,
        sort_type: Optional[Literal["0", "1"]] = None,
        publish_time: Optional[Literal["0", "1", "7", "30", "90", "180"]] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search TikTok videos by keyword.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            keyword: Search keyword (1-500 characters).
            cursor: Pagination cursor (default '0').
            count: Results per page (1-30).
            sort_type: '0' = relevance, '1' = most likes.
            publish_time: Age filter in days: 0 = all time, 1, 7, 30, 90, 180.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_search_videos", {"keyword": keyword, "cursor": cursor, "count": count, "sort_type": sort_type, "publish_time": publish_time}, extra)

    def search_users(
        self,
        keyword: str,
        *,
        cursor: Optional[str] = None,
        count: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search TikTok users by keyword.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            keyword: Search keyword (1-500 characters).
            cursor: Pagination cursor (default '0').
            count: Results per page (1-30).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_search_users", {"keyword": keyword, "cursor": cursor, "count": count}, extra)

    def hashtag(
        self,
        *,
        hashtag_name: Optional[str] = None,
        hashtag_id: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """TikTok hashtag details. Provide hashtag_name or hashtag_id.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            hashtag_name: Hashtag name (without the #).
            hashtag_id: Hashtag id.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_hashtag", {"hashtag_name": hashtag_name, "hashtag_id": hashtag_id}, extra)

    def hashtag_videos(
        self,
        hashtag_id: str,
        *,
        cursor: Optional[str] = None,
        count: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Videos for a TikTok hashtag.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            hashtag_id: Hashtag id.
            cursor: Pagination cursor (default '0').
            count: Results per page (1-30).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_hashtag_videos", {"hashtag_id": hashtag_id, "cursor": cursor, "count": count}, extra)

    def user_followers(
        self,
        sec_user_id: str,
        *,
        count: Optional[int] = None,
        page_token: Optional[str] = None,
        min_time: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Followers of a TikTok user.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            sec_user_id: TikTok sec_user_id.
            count: Results per page (1-20).
            page_token: Pagination token from a prior response.
            min_time: Minimum timestamp cursor.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_user_followers", {"sec_user_id": sec_user_id, "count": count, "page_token": page_token, "min_time": min_time}, extra)

    def user_followings(
        self,
        sec_user_id: str,
        *,
        count: Optional[int] = None,
        page_token: Optional[str] = None,
        min_time: Optional[int] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Accounts a TikTok user follows.

        Costs 1 credit. Returns the API response as a dict.

        Args:
            sec_user_id: TikTok sec_user_id.
            count: Results per page (1-20).
            page_token: Pagination token from a prior response.
            min_time: Minimum timestamp cursor.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("tiktok_user_followings", {"sec_user_id": sec_user_id, "count": count, "page_token": page_token, "min_time": min_time}, extra)

class _InstagramNamespace:
    """Instagram profile, media, and search endpoints."""

    def __init__(self, client: "ScavioClient") -> None:
        self._client = client

    def profile(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Instagram profile. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_profile", {"username": username, "user_id": user_id}, extra)

    def user_posts(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        count: Optional[int] = None,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Posts from an Instagram user. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            count: Results per page (1-50).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_user_posts", {"username": username, "user_id": user_id, "count": count, "cursor": cursor}, extra)

    def user_reels(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        count: Optional[int] = None,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Reels from an Instagram user. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            count: Results per page (1-50).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_user_reels", {"username": username, "user_id": user_id, "count": count, "cursor": cursor}, extra)

    def user_tagged(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        count: Optional[int] = None,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Posts an Instagram user is tagged in. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            count: Results per page (1-50).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_user_tagged", {"username": username, "user_id": user_id, "count": count, "cursor": cursor}, extra)

    def user_stories(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Active stories for an Instagram user. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_user_stories", {"username": username, "user_id": user_id}, extra)

    def post(
        self,
        *,
        url: Optional[str] = None,
        media_id: Optional[str] = None,
        shortcode: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """An Instagram post. Provide url, media_id, or shortcode. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            url: Full Instagram post URL.
            media_id: Instagram media id.
            shortcode: Instagram shortcode (from the post URL).
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_post", {"url": url, "media_id": media_id, "shortcode": shortcode}, extra)

    def post_comments(
        self,
        *,
        shortcode: Optional[str] = None,
        url: Optional[str] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[Literal["popular", "newest"]] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Comments on an Instagram post. Provide shortcode or url. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            shortcode: Instagram shortcode (from the post URL).
            url: Full Instagram post URL.
            cursor: Pagination cursor from a prior response.
            sort_order: Comment sort order.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_post_comments", {"shortcode": shortcode, "url": url, "cursor": cursor, "sort_order": sort_order}, extra)

    def comment_replies(
        self,
        media_id: str,
        comment_id: str,
        *,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Replies to an Instagram comment. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            media_id: Instagram media id.
            comment_id: Parent comment id.
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_comment_replies", {"media_id": media_id, "comment_id": comment_id, "cursor": cursor}, extra)

    def search_users(
        self,
        keyword: str,
        *,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search Instagram users by keyword. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            keyword: Search keyword (1-500 characters).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_search_users", {"keyword": keyword, "cursor": cursor}, extra)

    def search_hashtags(
        self,
        keyword: str,
        *,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Search Instagram hashtags by keyword. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            keyword: Search keyword (1-500 characters).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_search_hashtags", {"keyword": keyword, "cursor": cursor}, extra)

    def user_followers(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        count: Optional[int] = None,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Followers of an Instagram user. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            count: Results per page (1-100).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_user_followers", {"username": username, "user_id": user_id, "count": count, "cursor": cursor}, extra)

    def user_followings(
        self,
        *,
        username: Optional[str] = None,
        user_id: Optional[str] = None,
        count: Optional[int] = None,
        cursor: Optional[str] = None,
        **extra: Any,
    ) -> dict[str, Any]:
        """Accounts an Instagram user follows. Provide username or user_id. Costs 2 credits.

        Costs 2 credits. Returns the API response as a dict.

        Args:
            username: Instagram username (without the @).
            user_id: Instagram numeric user id.
            count: Results per page (1-100).
            cursor: Pagination cursor from a prior response.
            extra: Additional wire parameters passed through verbatim.
        """
        return self._client._call("instagram_user_followings", {"username": username, "user_id": user_id, "count": count, "cursor": cursor}, extra)
